<?php

// Copyright 2026 NDC Digital, LLC
// SPDX-License-Identifier: Apache-2.0
//
// Flametrench v0.1 conformance suite — PHP / PEST harness for the
// identity capability.
//
// Exercises verify_password against the cross-language Argon2id parity
// fixture vendored from
// github.com/flametrench/spec/conformance/fixtures/identity/.
// Tests under tests/conformance/fixtures/ are a snapshot; the
// drift-check CI job verifies they match the upstream spec repo.
//
// Why this fixture matters: the fixture's PHC hash was generated by the
// Node `argon2` package. PHP's `password_verify()` MUST accept it. If
// this test ever fails, password-based auth has become non-portable
// across SDKs — a bug Flametrench exists to prevent.

declare(strict_types=1);

use Flametrench\Identity\Mfa\RecoveryCodes;
use Flametrench\Identity\Mfa\Totp;
use Flametrench\Identity\PasswordHashing;

const IDENTITY_FIXTURES_DIR = __DIR__ . '/conformance/fixtures';

/**
 * @return array{spec_version:string, capability:string, operation:string,
 *     conformance_level:string, description:string, tests:array<int,array>}
 */
function loadIdentityFixture(string $relativePath): array
{
    $raw = file_get_contents(IDENTITY_FIXTURES_DIR . '/' . $relativePath);
    if ($raw === false) {
        throw new RuntimeException("Cannot read fixture: {$relativePath}");
    }
    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        throw new RuntimeException("Invalid JSON in fixture: {$relativePath}");
    }
    return $decoded;
}

// ─── identity.verify_password ───

describe(
    'Conformance · identity.verify_password [MUST]',
    function () {
        $fixture = loadIdentityFixture('identity/argon2id.json');
        foreach ($fixture['tests'] as $t) {
            it("[{$t['id']}] {$t['description']}", function () use ($t) {
                $result = PasswordHashing::verify(
                    $t['input']['phc_hash'],
                    $t['input']['candidate_password'],
                );
                expect($result)->toBe($t['expected']['result']);
            });
        }
    },
);

// ─── v0.2: identity.totp_compute (RFC 6238) ───

describe(
    'Conformance · identity.totp_compute [MUST] · RFC 6238',
    function () {
        $fixture = loadIdentityFixture('identity/mfa/totp-rfc6238.json');
        foreach ($fixture['tests'] as $t) {
            it("[{$t['id']}] {$t['description']}", function () use ($t) {
                $result = Totp::compute(
                    secret: $t['input']['secret_ascii'],
                    timestamp: $t['input']['timestamp'],
                    digits: $t['input']['digits'],
                    algorithm: $t['input']['algorithm'],
                );
                expect($result)->toBe($t['expected']['result']);
            });
        }
    },
);

// ─── v0.2: identity.generate_recovery_code (format predicate) ───

describe(
    'Conformance · identity.generate_recovery_code [MUST] · format',
    function () {
        $fixture = loadIdentityFixture('identity/mfa/recovery-code-format.json');
        foreach ($fixture['tests'] as $t) {
            it("[{$t['id']}] {$t['description']}", function () use ($t) {
                expect(RecoveryCodes::isValid($t['input']['code']))
                    ->toBe($t['expected']['result']);
            });
        }
    },
);
